Controllers/OgrenciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Permissions;
using System.Web;
using System.Web.Mvc;
using Mvc_Vize_Projesi.Models.Entity;

namespace Mvc_Vize_Projesi.Controllers
{
    public class OgrenciController : Controller
    {
        vize_mvcEntities2 db = new vize_mvcEntities2();
        // GET: Ogrenci
        public ActionResult Index()
        {
            var ogrenciler = db.Tbl_Ogrenci.ToList();
            return View(ogrenciler);
        }
        [HttpGet]
        public ActionResult YeniOgrenci()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniOgrenci(Tbl_Ogrenci p1)
        {
            db.Tbl_Ogrenci.Add(p1);
            db.SaveChanges();
            return View();
        }
        public ActionResult SIL(int id)
        {
            var ogrenci = db.Tbl_Ogrenci.Find(id);
            db.Tbl_Ogrenci.Remove(ogrenci);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult OgrenciGetir(int id) 
        {
            var ogr = db.Tbl_Ogrenci.Find(id);
            return View("OgrenciGetir", ogr);
        }
        public ActionResult Guncelle(Tbl_Ogrenci p1)
        {
            var ogr = db.Tbl_Ogrenci.Find(p1.ogreinciid);
            ogr.OgrenciBolum = p1.OgrenciBolum;
            ogr.OgrenciAdSoyad = p1.OgrenciAdSoyad;
            ogr.OgrenciNo = p1.OgrenciNo;
            ogr.OgrenciKredi = p1.OgrenciKredi;

            // Öğrencinin kredi sayısını kontrol et
            if (p1.OgrenciKredi <= 50)
            {
                // 50 kredi altında ise, hata mesajı ekleyin ve tekrar Guncelle sayfasını gösterin
                ModelState.AddModelError(string.Empty, "Öğrenci 50 kredi altında olduğu için mezun olamaz.");
                return View(p1);
            }

            // 50 kredi üstünde ise, mezun olmasına izin ver
            ogr.OgrenciMezun = true;

            if (ModelState.IsValid)
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            // Eğer model doğrulama başarısız olursa, formu tekrar göster
            return View(p1);
        }
    }
}

Views/Ogrenci/Guncelle.cshtml
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="alert alert-danger" role="alert">
    Öğrenci kredisi 50'den düşük olduğu için mezun olamaz.
</div>

Views/Ogrenci/Index.cshtml
@using Mvc_Vize_Projesi.Models.Entity;
@model List<Tbl_Ogrenci>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@{
    var AktifOgrenciler = Model.Where(ogr => !ogr.OgrenciMezun.HasValue || !ogr.OgrenciMezun.Value).ToList();
}

@*//guncelleme isleminde gerektigi icin mezun ogrenciler burada da tanimli*@

@{
    var MezunOgrenciler = Model.Where(ogr => ogr.OgrenciMezun.HasValue && ogr.OgrenciMezun.Value).ToList();
}




<table class="table table-bordered">
    <tr>
        <th>Ogrenci Id</th>
        <th>Ogrenci Bolum</th>
        <th>Ogrenci Ad Soyad</th>
        <th>Ogrenci No</th>
        <th>Ogrenci Kredi</th>
        <th>Mezun</th>
        <th>Sil</th>
        <th>Guncelle</th>
    </tr>
    <tbody>
        @foreach (var ogr in AktifOgrenciler)
        {
            <tr>
                <td>@ogr.ogreinciid</td>
                <td>@ogr.OgrenciBolum</td>
                <td>@ogr.OgrenciAdSoyad</td>
                <td>@ogr.OgrenciNo</td>
                <td>@ogr.OgrenciKredi</td>
                <td>@ogr.OgrenciMezun</td>
                <td><a href="/Ogrenci/Sil/@ogr.ogreinciid" class="btn btn-danger">Sil</a></td>
                <td><a href="/Ogrenci/OgrenciGetir/@ogr.ogreinciid" class="btn btn-success">Guncelle</a></td>
            </tr>
        }
    </tbody>
</table>
<a href="/Ogrenci/YeniOgrenci/" class="btn btn-primary">Yeni Ogrenci Ekle</a>

Views/Ogrenci/OgrenciGetir.cshtml
@model Mvc_Vize_Projesi.Models.Entity.Tbl_Ogrenci
@{
    ViewBag.Title = "OgrenciGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@{
    var bolumler = new List<SelectListItem>
{
        new SelectListItem { Text = "Bilgisayar", Value = "Bilgisayar" },
        new SelectListItem { Text = "Makine", Value = "Makine" },
    };

    var mezuniyetDurumlari = new List<SelectListItem>
{
        new SelectListItem { Text = "Mezun", Value = "True" },
        new SelectListItem { Text = "Mezun Değil", Value = "False" }
    };
}
@using (Html.BeginForm("Guncelle", "Ogrenci", FormMethod.Post))
{
    <div>
        @Html.LabelFor(m => m.ogreinciid)
        @Html.TextBoxFor(m => m.ogreinciid, new { @class = "form-control" })


        @Html.LabelFor(m => m.OgrenciBolum)
        @Html.DropDownListFor(m => m.OgrenciBolum, bolumler, "Lütfen bir bölüm seçiniz", new { @class = "form-control" })



        @Html.LabelFor(m => m.OgrenciAdSoyad)
        @Html.TextBoxFor(m => m.OgrenciAdSoyad, new { @class = "form-control" })


        @Html.LabelFor(m => m.OgrenciNo)
        @Html.TextBoxFor(m => m.OgrenciNo, new { @class = "form-control" })


        @Html.LabelFor(m => m.OgrenciKredi)
        @Html.TextBoxFor(m => m.OgrenciKredi, new { @class = "form-control" })



        @Html.Label("Mezuniyet Durumu")
        @Html.DropDownListFor(m => m.OgrenciMezun, mezuniyetDurumlari, "Mezuniyet Durumu Seçiniz", new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Ogrenci Guncelle</button>
    </div>
}

Views/Ogrenci/YeniOgrenci.cshtml
@{
    ViewBag.Title = "YeniOgrenci";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">

    <div>
        <label>Ogrenci Bolumu</label>
        @Html.DropDownList("OgrenciBolum", new SelectList(new List<SelectListItem>
{
new SelectListItem { Text = "Ogrenci Bolumunu Seçiniz", Value = "" },
new SelectListItem { Text = "Bilgisayar", Value = "Bilgisayar" },
new SelectListItem { Text = "Makine", Value = "Makine" },
}, "Value", "Text"), new { @class = "form-control" })
    </div>

    <div>
        <label>Ogrenci Adi Soyadi</label>
        <input type="text" class="form-control" name="OgrenciAdSoyad" />
    </div>
    <div>
        <label>Ogrenci No</label>
        <input type="text" class="form-control" name="OgrenciNo" />
    </div>
    <div>
        <label>Ogrenci Kredisi</label>
        <input type="text" class="form-control" name="OgrenciKredi" />
    </div>

    <div>
        <label>Ogrenci Mezuniyet</label>
        @Html.DropDownList("OgrenciMezun", new SelectList(new List<SelectListItem>
{
new SelectListItem { Text = "Ogrenci Mezuniyet Durumu", Value = "" },
new SelectListItem { Text = "Mezun", Value = "True" },
new SelectListItem { Text = "Degil", Value = "False" },
}, "Value", "Text"), new { @class = "form-control" })
    </div>


    <div style="margin-top:21px">
        <button class="btn btn-info">Ogrenci Ekle</button>
    </div>

</form>