Controllers/OgretmenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc_Vize_Projesi.Models.Entity;


namespace Mvc_Vize_Projesi.Controllers
{
    public class OgretmenController : Controller
    {
        // GET: Ogretmen
        vize_mvcEntities2 db = new vize_mvcEntities2();
        public ActionResult Index()
        {
            var ogretmenler = db.Tbl_Ogretmen.ToList();
            return View(ogretmenler);
        }
        [HttpGet]
        public ActionResult YeniOgretmen()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniOgretmen(Tbl_Ogretmen p1) 
        {
            db.Tbl_Ogretmen.Add(p1);
            db.SaveChanges();
            return View();
        }
        public ActionResult SIL(int id)
        {
            var ogretmen = db.Tbl_Ogretmen.Find(id);
            db.Tbl_Ogretmen.Remove(ogretmen);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult OgretmenGetir(int id)
        {
            var ogretmen = db.Tbl_Ogretmen.Find(id);
            return View("OgretmenGetir", ogretmen);
        }
        public ActionResult Guncelle(Tbl_Ogretmen p1)
        {
            var ogr = db.Tbl_Ogretmen.Find(p1.ogretmenid);
            ogr.OgretmenBolum = p1.OgretmenBolum;
            ogr.OgretmenAd = p1.OgretmenAd;
            ogr.OgretmenSoyad = p1.OgretmenSoyad;
            ogr.OgretmenGiris = p1.OgretmenGiris;
            ogr.OgretmenCikis = p1.OgretmenCikis;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Ogretmen/Index.cshtml
@using Mvc_Vize_Projesi.Models.Entity;
@model List<Tbl_Ogretmen>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Ogretmen Id</th>
        <th>Ogretmen Bolum</th>
        <th>Ogretmen Ad</th>
        <th>Ogretmen Soyad</th>
        <th>Ogretmen Giris</th>
        <th>Ogretmen Cikis</th>
    </tr>
    <tbody>
        @foreach (var ogretmen in Model)
        {
            <tr>
                <td>@ogretmen.ogretmenid</td>
                <td>@ogretmen.OgretmenBolum</td>
                <td>@ogretmen.OgretmenAd</td>
                <td>@ogretmen.OgretmenSoyad</td>
                <td>@ogretmen.OgretmenGiris</td>
                <td>@ogretmen.OgretmenCikis</td>
                <td><a href="/Ogretmen/SIL/@ogretmen.ogretmenid" class="btn btn-danger">Sil</a></td>
                <td><a href="/Ogretmen/OgertmenGetir/@ogretmen.ogretmenid" class="btn btn-success">Guncelle</a></td>
            </tr>
        }
    </tbody>
</table>
<a href="/Ogretmen/YeniOgretmen/" class="btn btn-primary">Yeni Ogretmen Ekle</a>

Views/Ogretmen/OgretmenGetir.cshtml
@model Mvc_Vize_Projesi.Models.Entity.Tbl_Ogretmen

@{
    ViewBag.Title = "OgretmenGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@{
    var bolumler = new List<SelectListItem>
{
        new SelectListItem { Text = "Bilgisayar", Value = "Bilgisayar" },
        new SelectListItem { Text = "Makine", Value = "Makine" },
    };
}

@using (Html.BeginForm("Guncelle", "Ogretmen", FormMethod.Post))
{
    <div>
        @Html.LabelFor(m => m.ogretmenid)
        @Html.TextBoxFor(m => m.ogretmenid, new { @class = "form-control" })


        @Html.LabelFor(m => m.OgretmenBolum)
        @Html.DropDownListFor(m => m.OgretmenBolum, bolumler, "Lütfen bir bölüm seçiniz", new { @class = "form-control" })



        @Html.LabelFor(m => m.OgretmenAd)
        @Html.TextBoxFor(m => m.OgretmenAd, new { @class = "form-control" })


        @Html.LabelFor(m => m.OgretmenSoyad)
        @Html.TextBoxFor(m => m.OgretmenSoyad, new { @class = "form-control" })


        @Html.LabelFor(m => m.OgretmenGiris)
        @Html.EditorFor(m => m.OgretmenGiris, new { @class = "form-control" })

        @Html.LabelFor(m => m.OgretmenCikis)
        @Html.EditorFor(m => m.OgretmenCikis, new { @class = "form-control" })




    </div>
    <div>
        <button class="btn btn-warning">Ogretmen Guncelle</button>
    </div>
}

Views/Ogretmen/YeniOgretmen.cshtml
@{
    ViewBag.Title = "YeniOgretmen";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post" class="form-group">

    <div>
        <label>Ogretmen Bolumu</label>
        @Html.DropDownList("OgretmenBolum", new SelectList(new List<SelectListItem>
{
new SelectListItem { Text = "Ogretmen Bolumunu Seçiniz", Value = "" },
new SelectListItem { Text = "Bilgisayar", Value = "Bilgisayar" },
new SelectListItem { Text = "Makine", Value = "Makine" },
}, "Value", "Text"), new { @class = "form-control" })
    </div>

    <div>
        <label>Ogretmen Adi</label>
        <input type="text" class="form-control" name="OgretmenAd" />
    </div>
    <div>
        <label>Ogretmen Soyadi</label>
        <input type="text" class="form-control" name="OgretmenSoyad" />
    </div>
    <div>
        <label>Ogretmen Giris Tarihi</label>
        <input type="date" class="form-control" name="OgretmenGiris" />
    </div>
    <div>
        <label>Ogretmen Cikis Tarihi</label>
        <input type="date" class="form-control" name="OgretmenCikis" />
    </div>
    <div style="margin-top:21px">
        <button class="btn btn-info">Ogretmen Ekle</button>
    </div>
</form>